[CmdletBinding()]
param(
    [switch]$IncludeSidecars,
    [ValidateSet('Fastest', 'Optimal', 'NoCompression')]
    [string]$CompressionLevel = 'Fastest'
)

$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$packRoot = Join-Path $root 'resource-packs'
$manifest = Get-Content (Join-Path $packRoot 'manifest.json') -Raw | ConvertFrom-Json
$hashLines = @()

foreach ($pack in $manifest.packs) {
    if ($pack.id -eq 'sidecars-win-x64' -and -not $IncludeSidecars) {
        continue
    }

    $stage = Join-Path $root ".tmp\resource-packs\$($pack.id)"
    $archive = Join-Path $packRoot $pack.file
    Remove-Item $stage -Recurse -Force -ErrorAction SilentlyContinue
    Remove-Item $archive -Force -ErrorAction SilentlyContinue
    New-Item $stage -ItemType Directory -Force | Out-Null

    try {
        foreach ($relativePath in $pack.paths) {
            $relative = $relativePath -replace '/', '\'
            $source = Join-Path $root $relative
            if (-not (Test-Path $source)) {
                throw "Missing resource path: $relativePath"
            }
            $target = Join-Path $stage $relative
            New-Item (Split-Path $target -Parent) -ItemType Directory -Force | Out-Null
            Copy-Item $source $target -Recurse -Force
        }

        Compress-Archive -Path (Join-Path $stage '*') -DestinationPath $archive -CompressionLevel $CompressionLevel
        $hash = (Get-FileHash $archive -Algorithm SHA256).Hash.ToLowerInvariant()
        $hashLines += "$hash  $($pack.file)"
        $size = [math]::Round((Get-Item $archive).Length / 1MB, 1)
        Write-Host "Created $($pack.file) ($size MiB)"
    }
    finally {
        Remove-Item $stage -Recurse -Force -ErrorAction SilentlyContinue
    }
}

$checksumPath = Join-Path $packRoot 'checksums.sha256'
@('# Generated by scripts/pack-resources.ps1') + $hashLines |
    Set-Content $checksumPath -Encoding utf8
Write-Host "Checksums: $checksumPath"
